#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Saturation_Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertRef_UL_Item(Ref_UL_Item instance);
  partial void UpdateRef_UL_Item(Ref_UL_Item instance);
  partial void DeleteRef_UL_Item(Ref_UL_Item instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Saturation_DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Ref_UL_Item> Ref_UL_Items
	{
		get
		{
			return this.GetTable<Ref_UL_Item>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ref_UL_Item")]
public partial class Ref_UL_Item : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _item_code;
	
	private string _item_name;
	
	private string _base_tag;
	
	private string _classification;
	
	private string _class;
	
	private string _division_code;
	
	private string _division_name;
	
	private string _glu_cluster_code;
	
	private string _glu_cluster_name;
	
	private string _glu_sub_group;
	
	private string _glu_code;
	
	private string _glu_name;
	
	private string _category_code;
	
	private string _category_name;
	
	private string _sub_brand_code;
	
	private string _sub_brand_name;
	
	private string _brand_code;
	
	private string _brand_name;
	
	private string _franchise_code;
	
	private string _franchise_name;
	
	private string _segment_code;
	
	private string _segment_name;
	
	private string _sub_segment_code;
	
	private string _sub_segment_name;
	
	private string _molecule_code;
	
	private string _molecule_name;
	
	private char _cluster_code;
	
	private string _cluster_name;
	
	private string _item_status;
	
	private string _item_status_name;
	
	private string _class_name;
	
	private string _line_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onitem_codeChanging(string value);
    partial void Onitem_codeChanged();
    partial void Onitem_nameChanging(string value);
    partial void Onitem_nameChanged();
    partial void Onbase_tagChanging(string value);
    partial void Onbase_tagChanged();
    partial void OnclassificationChanging(string value);
    partial void OnclassificationChanged();
    partial void OnclassChanging(string value);
    partial void OnclassChanged();
    partial void Ondivision_codeChanging(string value);
    partial void Ondivision_codeChanged();
    partial void Ondivision_nameChanging(string value);
    partial void Ondivision_nameChanged();
    partial void Onglu_cluster_codeChanging(string value);
    partial void Onglu_cluster_codeChanged();
    partial void Onglu_cluster_nameChanging(string value);
    partial void Onglu_cluster_nameChanged();
    partial void Onglu_sub_groupChanging(string value);
    partial void Onglu_sub_groupChanged();
    partial void Onglu_codeChanging(string value);
    partial void Onglu_codeChanged();
    partial void Onglu_nameChanging(string value);
    partial void Onglu_nameChanged();
    partial void Oncategory_codeChanging(string value);
    partial void Oncategory_codeChanged();
    partial void Oncategory_nameChanging(string value);
    partial void Oncategory_nameChanged();
    partial void Onsub_brand_codeChanging(string value);
    partial void Onsub_brand_codeChanged();
    partial void Onsub_brand_nameChanging(string value);
    partial void Onsub_brand_nameChanged();
    partial void Onbrand_codeChanging(string value);
    partial void Onbrand_codeChanged();
    partial void Onbrand_nameChanging(string value);
    partial void Onbrand_nameChanged();
    partial void Onfranchise_codeChanging(string value);
    partial void Onfranchise_codeChanged();
    partial void Onfranchise_nameChanging(string value);
    partial void Onfranchise_nameChanged();
    partial void Onsegment_codeChanging(string value);
    partial void Onsegment_codeChanged();
    partial void Onsegment_nameChanging(string value);
    partial void Onsegment_nameChanged();
    partial void Onsub_segment_codeChanging(string value);
    partial void Onsub_segment_codeChanged();
    partial void Onsub_segment_nameChanging(string value);
    partial void Onsub_segment_nameChanged();
    partial void Onmolecule_codeChanging(string value);
    partial void Onmolecule_codeChanged();
    partial void Onmolecule_nameChanging(string value);
    partial void Onmolecule_nameChanged();
    partial void Oncluster_codeChanging(char value);
    partial void Oncluster_codeChanged();
    partial void Oncluster_nameChanging(string value);
    partial void Oncluster_nameChanged();
    partial void Onitem_statusChanging(string value);
    partial void Onitem_statusChanged();
    partial void Onitem_status_nameChanging(string value);
    partial void Onitem_status_nameChanged();
    partial void Onclass_nameChanging(string value);
    partial void Onclass_nameChanged();
    partial void Online_nameChanging(string value);
    partial void Online_nameChanged();
    #endregion
	
	public Ref_UL_Item()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_code", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string item_code
	{
		get
		{
			return this._item_code;
		}
		set
		{
			if ((this._item_code != value))
			{
				this.Onitem_codeChanging(value);
				this.SendPropertyChanging();
				this._item_code = value;
				this.SendPropertyChanged("item_code");
				this.Onitem_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string item_name
	{
		get
		{
			return this._item_name;
		}
		set
		{
			if ((this._item_name != value))
			{
				this.Onitem_nameChanging(value);
				this.SendPropertyChanging();
				this._item_name = value;
				this.SendPropertyChanged("item_name");
				this.Onitem_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_base_tag", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string base_tag
	{
		get
		{
			return this._base_tag;
		}
		set
		{
			if ((this._base_tag != value))
			{
				this.Onbase_tagChanging(value);
				this.SendPropertyChanging();
				this._base_tag = value;
				this.SendPropertyChanged("base_tag");
				this.Onbase_tagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classification", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string classification
	{
		get
		{
			return this._classification;
		}
		set
		{
			if ((this._classification != value))
			{
				this.OnclassificationChanging(value);
				this.SendPropertyChanging();
				this._classification = value;
				this.SendPropertyChanged("classification");
				this.OnclassificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string @class
	{
		get
		{
			return this._class;
		}
		set
		{
			if ((this._class != value))
			{
				this.OnclassChanging(value);
				this.SendPropertyChanging();
				this._class = value;
				this.SendPropertyChanged("@class");
				this.OnclassChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_code", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
	public string division_code
	{
		get
		{
			return this._division_code;
		}
		set
		{
			if ((this._division_code != value))
			{
				this.Ondivision_codeChanging(value);
				this.SendPropertyChanging();
				this._division_code = value;
				this.SendPropertyChanged("division_code");
				this.Ondivision_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_name", DbType="VarChar(30)")]
	public string division_name
	{
		get
		{
			return this._division_name;
		}
		set
		{
			if ((this._division_name != value))
			{
				this.Ondivision_nameChanging(value);
				this.SendPropertyChanging();
				this._division_name = value;
				this.SendPropertyChanged("division_name");
				this.Ondivision_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glu_cluster_code", DbType="Char(4)")]
	public string glu_cluster_code
	{
		get
		{
			return this._glu_cluster_code;
		}
		set
		{
			if ((this._glu_cluster_code != value))
			{
				this.Onglu_cluster_codeChanging(value);
				this.SendPropertyChanging();
				this._glu_cluster_code = value;
				this.SendPropertyChanged("glu_cluster_code");
				this.Onglu_cluster_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glu_cluster_name", DbType="VarChar(30)")]
	public string glu_cluster_name
	{
		get
		{
			return this._glu_cluster_name;
		}
		set
		{
			if ((this._glu_cluster_name != value))
			{
				this.Onglu_cluster_nameChanging(value);
				this.SendPropertyChanging();
				this._glu_cluster_name = value;
				this.SendPropertyChanged("glu_cluster_name");
				this.Onglu_cluster_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glu_sub_group", DbType="VarChar(30)")]
	public string glu_sub_group
	{
		get
		{
			return this._glu_sub_group;
		}
		set
		{
			if ((this._glu_sub_group != value))
			{
				this.Onglu_sub_groupChanging(value);
				this.SendPropertyChanging();
				this._glu_sub_group = value;
				this.SendPropertyChanged("glu_sub_group");
				this.Onglu_sub_groupChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glu_code", DbType="Char(4)")]
	public string glu_code
	{
		get
		{
			return this._glu_code;
		}
		set
		{
			if ((this._glu_code != value))
			{
				this.Onglu_codeChanging(value);
				this.SendPropertyChanging();
				this._glu_code = value;
				this.SendPropertyChanged("glu_code");
				this.Onglu_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glu_name", DbType="VarChar(30)")]
	public string glu_name
	{
		get
		{
			return this._glu_name;
		}
		set
		{
			if ((this._glu_name != value))
			{
				this.Onglu_nameChanging(value);
				this.SendPropertyChanging();
				this._glu_name = value;
				this.SendPropertyChanged("glu_name");
				this.Onglu_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_code", DbType="Char(2) NOT NULL", CanBeNull=false)]
	public string category_code
	{
		get
		{
			return this._category_code;
		}
		set
		{
			if ((this._category_code != value))
			{
				this.Oncategory_codeChanging(value);
				this.SendPropertyChanging();
				this._category_code = value;
				this.SendPropertyChanged("category_code");
				this.Oncategory_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="VarChar(35)")]
	public string category_name
	{
		get
		{
			return this._category_name;
		}
		set
		{
			if ((this._category_name != value))
			{
				this.Oncategory_nameChanging(value);
				this.SendPropertyChanging();
				this._category_name = value;
				this.SendPropertyChanged("category_name");
				this.Oncategory_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_brand_code", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
	public string sub_brand_code
	{
		get
		{
			return this._sub_brand_code;
		}
		set
		{
			if ((this._sub_brand_code != value))
			{
				this.Onsub_brand_codeChanging(value);
				this.SendPropertyChanging();
				this._sub_brand_code = value;
				this.SendPropertyChanged("sub_brand_code");
				this.Onsub_brand_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_brand_name", DbType="VarChar(30)")]
	public string sub_brand_name
	{
		get
		{
			return this._sub_brand_name;
		}
		set
		{
			if ((this._sub_brand_name != value))
			{
				this.Onsub_brand_nameChanging(value);
				this.SendPropertyChanging();
				this._sub_brand_name = value;
				this.SendPropertyChanged("sub_brand_name");
				this.Onsub_brand_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_code", DbType="Char(3)")]
	public string brand_code
	{
		get
		{
			return this._brand_code;
		}
		set
		{
			if ((this._brand_code != value))
			{
				this.Onbrand_codeChanging(value);
				this.SendPropertyChanging();
				this._brand_code = value;
				this.SendPropertyChanged("brand_code");
				this.Onbrand_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_name", DbType="VarChar(30)")]
	public string brand_name
	{
		get
		{
			return this._brand_name;
		}
		set
		{
			if ((this._brand_name != value))
			{
				this.Onbrand_nameChanging(value);
				this.SendPropertyChanging();
				this._brand_name = value;
				this.SendPropertyChanged("brand_name");
				this.Onbrand_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_franchise_code", DbType="VarChar(15)")]
	public string franchise_code
	{
		get
		{
			return this._franchise_code;
		}
		set
		{
			if ((this._franchise_code != value))
			{
				this.Onfranchise_codeChanging(value);
				this.SendPropertyChanging();
				this._franchise_code = value;
				this.SendPropertyChanged("franchise_code");
				this.Onfranchise_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_franchise_name", DbType="VarChar(35)")]
	public string franchise_name
	{
		get
		{
			return this._franchise_name;
		}
		set
		{
			if ((this._franchise_name != value))
			{
				this.Onfranchise_nameChanging(value);
				this.SendPropertyChanging();
				this._franchise_name = value;
				this.SendPropertyChanged("franchise_name");
				this.Onfranchise_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segment_code", DbType="VarChar(15)")]
	public string segment_code
	{
		get
		{
			return this._segment_code;
		}
		set
		{
			if ((this._segment_code != value))
			{
				this.Onsegment_codeChanging(value);
				this.SendPropertyChanging();
				this._segment_code = value;
				this.SendPropertyChanged("segment_code");
				this.Onsegment_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segment_name", DbType="VarChar(30)")]
	public string segment_name
	{
		get
		{
			return this._segment_name;
		}
		set
		{
			if ((this._segment_name != value))
			{
				this.Onsegment_nameChanging(value);
				this.SendPropertyChanging();
				this._segment_name = value;
				this.SendPropertyChanged("segment_name");
				this.Onsegment_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_segment_code", DbType="VarChar(15)")]
	public string sub_segment_code
	{
		get
		{
			return this._sub_segment_code;
		}
		set
		{
			if ((this._sub_segment_code != value))
			{
				this.Onsub_segment_codeChanging(value);
				this.SendPropertyChanging();
				this._sub_segment_code = value;
				this.SendPropertyChanged("sub_segment_code");
				this.Onsub_segment_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_segment_name", DbType="VarChar(30)")]
	public string sub_segment_name
	{
		get
		{
			return this._sub_segment_name;
		}
		set
		{
			if ((this._sub_segment_name != value))
			{
				this.Onsub_segment_nameChanging(value);
				this.SendPropertyChanging();
				this._sub_segment_name = value;
				this.SendPropertyChanged("sub_segment_name");
				this.Onsub_segment_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_molecule_code", DbType="VarChar(15)")]
	public string molecule_code
	{
		get
		{
			return this._molecule_code;
		}
		set
		{
			if ((this._molecule_code != value))
			{
				this.Onmolecule_codeChanging(value);
				this.SendPropertyChanging();
				this._molecule_code = value;
				this.SendPropertyChanged("molecule_code");
				this.Onmolecule_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_molecule_name", DbType="VarChar(255)")]
	public string molecule_name
	{
		get
		{
			return this._molecule_name;
		}
		set
		{
			if ((this._molecule_name != value))
			{
				this.Onmolecule_nameChanging(value);
				this.SendPropertyChanging();
				this._molecule_name = value;
				this.SendPropertyChanged("molecule_name");
				this.Onmolecule_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cluster_code", DbType="Char(1) NOT NULL")]
	public char cluster_code
	{
		get
		{
			return this._cluster_code;
		}
		set
		{
			if ((this._cluster_code != value))
			{
				this.Oncluster_codeChanging(value);
				this.SendPropertyChanging();
				this._cluster_code = value;
				this.SendPropertyChanged("cluster_code");
				this.Oncluster_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cluster_name", DbType="VarChar(40)")]
	public string cluster_name
	{
		get
		{
			return this._cluster_name;
		}
		set
		{
			if ((this._cluster_name != value))
			{
				this.Oncluster_nameChanging(value);
				this.SendPropertyChanging();
				this._cluster_name = value;
				this.SendPropertyChanged("cluster_name");
				this.Oncluster_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_status", DbType="Char(2) NOT NULL", CanBeNull=false)]
	public string item_status
	{
		get
		{
			return this._item_status;
		}
		set
		{
			if ((this._item_status != value))
			{
				this.Onitem_statusChanging(value);
				this.SendPropertyChanging();
				this._item_status = value;
				this.SendPropertyChanged("item_status");
				this.Onitem_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_status_name", DbType="VarChar(50)")]
	public string item_status_name
	{
		get
		{
			return this._item_status_name;
		}
		set
		{
			if ((this._item_status_name != value))
			{
				this.Onitem_status_nameChanging(value);
				this.SendPropertyChanging();
				this._item_status_name = value;
				this.SendPropertyChanged("item_status_name");
				this.Onitem_status_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_name", DbType="VarChar(30)")]
	public string class_name
	{
		get
		{
			return this._class_name;
		}
		set
		{
			if ((this._class_name != value))
			{
				this.Onclass_nameChanging(value);
				this.SendPropertyChanging();
				this._class_name = value;
				this.SendPropertyChanged("class_name");
				this.Onclass_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_line_name", DbType="VarChar(30)")]
	public string line_name
	{
		get
		{
			return this._line_name;
		}
		set
		{
			if ((this._line_name != value))
			{
				this.Online_nameChanging(value);
				this.SendPropertyChanging();
				this._line_name = value;
				this.SendPropertyChanged("line_name");
				this.Online_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
